# coding=utf-8
timezone: Asia/Shanghai
# Site settings
email: zhao@zhao.stream
baseurl: ""
paginate: 20
paginate_path: "/pages/page-:num/"


# SEO settings
title: ZHAO'S WEBLOG ☁
description: 原来你也在这里……
twitter_username: zhaohao
disqus_username: zhaohao

social:
  twitter: https://twitter.com/zhaohao
  telegram: https://telegram.me/zhaohao
  facebook: https://facebook.com/haozhao
  instagram: https://www.instagram.com/hao.zhao/


# Build settings
include: ["_categories"]
exclude: ["Gemfile.lock", "README.md", "LICENSE.txt"]
markdown: kramdown
highlighter: rouge
permalink: note-:title.html

# Sass
sass:
  style: compressed

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  startings: [html, head, body]
  profile: false

# Gems
plugins: [jekyll-paginate, jekyll-sitemap]